config system global
    set hostname "FGT200F-DEMO"
    set alias "FortiGate 200F Demo - Education Lab"
    set timezone 12
    set admintimeout 60
    set gui-theme mariner
    set gui-device-latitude 40.7128
    set gui-device-longitude -74.0060
end

config system settings
    set gui-multiple-interface-policy enable
    set allow-subnet-overlap disable
    set asymroute disable
end
