config firewall service custom
    edit "SRV-DNS-TCP"
        set protocol TCP/UDP/SCTP
        set tcp-portrange 53
    next
    edit "SRV-DNS-UDP"
        set protocol TCP/UDP/SCTP
        set udp-portrange 53
    next
    edit "SRV-NTP"
        set protocol TCP/UDP/SCTP
        set udp-portrange 123
    next
    edit "SRV-LDAP"
        set protocol TCP/UDP/SCTP
        set tcp-portrange 389
    next
    edit "SRV-LDAPS"
        set protocol TCP/UDP/SCTP
        set tcp-portrange 636
    next
    edit "SRV-KERBEROS"
        set protocol TCP/UDP/SCTP
        set tcp-portrange 88
        set udp-portrange 88
    next
    edit "SRV-HTTP"
        set protocol TCP/UDP/SCTP
        set tcp-portrange 80
    next
    edit "SRV-HTTPS"
        set protocol TCP/UDP/SCTP
        set tcp-portrange 443
    next
    edit "SRV-WINRM"
        set protocol TCP/UDP/SCTP
        set tcp-portrange 5985-5986
    next
    edit "SRV-RDP"
        set protocol TCP/UDP/SCTP
        set tcp-portrange 3389
    next
    edit "SRV-SSH"
        set protocol TCP/UDP/SCTP
        set tcp-portrange 22
    next
    edit "SRV-SMB"
        set protocol TCP/UDP/SCTP
        set tcp-portrange 445
    next
    edit "SRV-SYSLOG"
        set protocol TCP/UDP/SCTP
        set udp-portrange 514
    next
    edit "SRV-SNMP"
        set protocol TCP/UDP/SCTP
        set udp-portrange 161-162
    next
    edit "SRV-MSSQL"
        set protocol TCP/UDP/SCTP
        set tcp-portrange 1433
    next
    edit "SRV-POSTGRES"
        set protocol TCP/UDP/SCTP
        set tcp-portrange 5432
    next
    edit "SRV-MYSQL"
        set protocol TCP/UDP/SCTP
        set tcp-portrange 3306
    next
    edit "SRV-ORACLE"
        set protocol TCP/UDP/SCTP
        set tcp-portrange 1521
    next
    edit "SRV-SFTP"
        set protocol TCP/UDP/SCTP
        set tcp-portrange 22
    next
    edit "SRV-SIP"
        set protocol TCP/UDP/SCTP
        set tcp-portrange 5060-5061
        set udp-portrange 5060-5061
    next
    edit "SRV-RTP"
        set protocol TCP/UDP/SCTP
        set udp-portrange 10000-20000
    next
end

config firewall service group
    edit "SRV-GRP-DNS"
        set member "SRV-DNS-TCP" "SRV-DNS-UDP"
    next
    edit "SRV-GRP-NTP"
        set member "SRV-NTP"
    next
    edit "SRV-GRP-AD"
        set member "SRV-LDAP" "SRV-LDAPS" "SRV-KERBEROS" "SRV-DNS-TCP" "SRV-DNS-UDP"
    next
    edit "SRV-GRP-WEB"
        set member "SRV-HTTP" "SRV-HTTPS"
    next
    edit "SRV-GRP-PROXY-UPDATES"
        set member "SRV-HTTP" "SRV-HTTPS"
    next
    edit "SRV-GRP-REMOTE-ADMIN"
        set member "SRV-SSH" "SRV-RDP" "SRV-WINRM"
    next
    edit "SRV-GRP-FILE"
        set member "SRV-SMB" "SRV-HTTPS"
    next
    edit "SRV-GRP-MONITORING"
        set member "SRV-SNMP" "SRV-SYSLOG"
    next
    edit "SRV-GRP-DB-ERP"
        set member "SRV-MSSQL"
    next
    edit "SRV-GRP-DB-CRM"
        set member "SRV-POSTGRES"
    next
    edit "SRV-GRP-DB-HR"
        set member "SRV-ORACLE"
    next
    edit "SRV-GRP-DB-HIST"
        set member "SRV-MYSQL"
    next
    edit "SRV-GRP-VOICE"
        set member "SRV-SIP" "SRV-RTP"
    next
    edit "SRV-GRP-PARTNER"
        set member "SRV-HTTPS" "SRV-SFTP"
    next
end
