config system zone
    edit "ZN-INTERNET-EGRESS"
        set interface "wan1" "wan2"
        set intrazone deny
    next
    edit "ZN-BUS-HR"
        set interface "vlan010_hr"
        set intrazone allow
    next
    edit "ZN-BUS-FIN"
        set interface "vlan020_fin"
        set intrazone allow
    next
    edit "ZN-BUS-SALES"
        set interface "vlan030_sales"
        set intrazone allow
    next
    edit "ZN-BUS-MKT"
        set interface "vlan040_mkt"
        set intrazone allow
    next
    edit "ZN-BUS-ENG"
        set interface "vlan050_eng"
        set intrazone allow
    next
    edit "ZN-BUS-RND"
        set interface "vlan060_rnd"
        set intrazone allow
    next
    edit "ZN-BUS-ERP"
        set interface "vlan070_erp"
        set intrazone allow
    next
    edit "ZN-BUS-CRM"
        set interface "vlan080_crm"
        set intrazone allow
    next
    edit "ZN-BUS-VOICE"
        set interface "vlan090_voice"
        set intrazone allow
    next
    edit "ZN-BUS-CORP-WIFI"
        set interface "vlan100_corpwifi"
        set intrazone allow
    next
    edit "ZN-BUS-MGMT"
        set interface "vlan110_mgmt"
        set intrazone allow
    next
    edit "ZN-BUS-GUEST-WIFI"
        set interface "vlan120_guest"
        set intrazone allow
    next
    edit "ZN-BUS-DATA"
        set interface "vlan130_data"
        set intrazone allow
    next
    edit "ZN-BUS-LOG"
        set interface "vlan140_log"
        set intrazone allow
    next
    edit "ZN-OT-SCADA"
        set interface "vlan210_scada"
        set intrazone allow
    next
    edit "ZN-OT-PLC"
        set interface "vlan220_plc"
        set intrazone allow
    next
    edit "ZN-OT-HIST"
        set interface "vlan230_hist"
        set intrazone allow
    next
    edit "ZN-OT-BMS"
        set interface "vlan240_bms"
        set intrazone allow
    next
    edit "ZN-OT-SAFETY"
        set interface "vlan250_safety"
        set intrazone allow
    next
    edit "ZN-OT-MFG"
        set interface "vlan260_mfg"
        set intrazone allow
    next
    edit "ZN-OT-QA"
        set interface "vlan270_qa"
        set intrazone allow
    next
    edit "ZN-OT-CCTV"
        set interface "vlan280_cctv"
        set intrazone allow
    next
    edit "ZN-DMZ-WEB"
        set interface "vlan310_webdmz"
        set intrazone allow
    next
    edit "ZN-DMZ-APP"
        set interface "vlan320_appdmz"
        set intrazone allow
    next
    edit "ZN-DMZ-DB"
        set interface "vlan330_dbdmz"
        set intrazone allow
    next
    edit "ZN-DMZ-PARTNER"
        set interface "vlan340_partner"
        set intrazone allow
    next
    edit "ZN-DMZ-REMOTE"
        set interface "vlan350_remote"
        set intrazone allow
    next
    edit "ZN-DMZ-SHARED"
        set interface "vlan360_shared"
        set intrazone allow
    next
end
